LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_SUFFIX:=.a
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE:=libcrypto_igs
LOCAL_SRC_FILES :=libcrypto.a
#LOCAL_MULTILIB:=both
LOCAL_PRELINK_MODULE:=false
#LOCAL_MODULE_PATH   := $(PRODUCT_OUT)/system/lib64
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)

LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_SUFFIX:=.a
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE:=libssl_igs
LOCAL_SRC_FILES :=libssl.a
#LOCAL_MULTILIB:=both
LOCAL_PRELINK_MODULE:=false
#LOCAL_MODULE_PATH   := $(PRODUCT_OUT)/system/lib64
include $(BUILD_PREBUILT)

